# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       xorg-x11-proto-resourceproto
Summary:    X.Org X11 Protocol resourceproto
Version:    1.2.0
Release:    0
Group:      Development/System
License:    MIT
URL:        http://www.x.org
Source0:    http://xorg.freedesktop.org/releases/individual/proto/resourceproto-%{version}.tar.bz2
Source100:  xorg-x11-proto-resourceproto.yaml
Provides:   resourceproto


%description
This extension defines a protocol that allows a client to query the  X  server
about its usage of various resources.




%prep
%setup -q -n resourceproto-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --libdir=%{_datadir}

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%{_datadir}/pkgconfig/resourceproto.pc
%{_includedir}/X11/extensions/XResproto.h
%doc %{_docdir}/resourceproto/resproto.txt
# << files


